ALTER TABLE users ADD COLUMN languages VARCHAR(200);

ALTER TABLE chats ADD COLUMN user1_shared_contacts BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE chats ADD COLUMN user2_shared_contacts BOOLEAN NOT NULL DEFAULT FALSE;
